In [1]:
import torch

In [ ]:
x = torch.arange(12)
x

torch.Size([12])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4))
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
x+y, x-y, x*y, x/y

(tensor([[ 8, 10, 12],
         [14, 16, 18]]),
 tensor([[-6, -6, -6],
         [-6, -6, -6]]),
 tensor([[ 7, 16, 27],
         [40, 55, 72]]),
 tensor([[0.1429, 0.2500, 0.3333],
         [0.4000, 0.4545, 0.5000]]))

In [8]:
torch.cat([x,y], dim=0)  # concatenate along rows
torch.cat([x,y], dim=1)  # concatenate along columns

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

In [9]:
x == y

tensor([[False, False, False],
        [False, False, False]])

In [10]:
x.sum()

tensor(21)

In [11]:
x[-1]

tensor([4, 5, 6])

In [12]:
x[1:3]

tensor([[4, 5, 6]])

In [13]:
x[1,2] = 99
x

tensor([[ 1,  2,  3],
        [ 4,  5, 99]])

In [15]:
x[0:2,:] = 12
x

tensor([[12, 12, 12],
        [12, 12, 12]])

In [16]:
before = id(y)
y = y + x
id(y) == before

False

In [ ]:
z = torch.empty_like(x)
z[:] = x + y
z
# z += x

In [20]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
# 插值
import pandas as pd
data = torch.arange(12, dtype=torch.float32)
data = data.reshape(4, 3)
data = pd.DataFrame(data.numpy(), columns=['a', 'b', 'c'])
# print(data)
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# print(inputs)
# print(outputs)
inputs = inputs.fillna(inputs.mean())   # 用均值填充缺失值
# print(inputs)
inputs = pd.get_dummies(inputs, dummy_na=True)  # 独热编码
# print(inputs)

x,y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x,y

(tensor([[ 0.,  1.],
         [ 3.,  4.],
         [ 6.,  7.],
         [ 9., 10.]]),
 tensor([ 2.,  5.,  8., 11.]))