In [1]:
import torch
import pandas as pd
import numpy as np

In [ ]:
A = torch.arange(20).reshape(5,4)
A.T # Transpose

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
B == B.T  # Check symmetry
A = B.clone()
A.sum(axis=1)  # Sum all elements

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


tensor([ 6,  6, 12])

In [15]:
print(B.float().mean() ) # Mean of all elements
C = B.sum()/B.numel()  # Alternative way to compute mean
C

tensor(2.6667)


tensor(2.6667)

In [18]:
sum_B = B.sum(axis=1, keepdim=True)
print(sum_B)
B / sum_B  # Normalize rows to sum to 1

tensor([[ 6],
        [ 6],
        [12]])


tensor([[0.1667, 0.3333, 0.5000],
        [0.3333, 0.0000, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [19]:
B.cumsum(axis=0) # Cumulative sum along rows

tensor([[ 1,  2,  3],
        [ 3,  2,  7],
        [ 6,  6, 12]])

In [34]:
# Linear algebra operations
x = torch.ones(3, dtype=torch.float32)
y = torch.randn((1,2,3), dtype=torch.float32)
x, y, # torch.dot(x, y) # Dot product

(tensor([1., 1., 1.]),
 tensor([[[-0.3854, -1.2704,  1.3633],
          [-0.7043, -0.2405, -0.5592]]]))

In [ ]:
B.shape, x.shape, torch.mv(B.float(), x)  # Matrix-vector product

(torch.Size([3, 3]), torch.Size([3]), tensor([ 6.,  6., 12.]))

In [28]:
torch.mm(A.float(), B.float())  # Matrix-matrix product

tensor([[14., 14., 26.],
        [14., 20., 26.],
        [26., 26., 50.]])

In [29]:
torch.norm(torch.ones(4, dtype=torch.float32))  # Vector norm

tensor(2.)

In [ ]:
torch.norm(A.float())  # Frobenius norm

tensor(9.1652)

In [31]:
torch.abs(A).sum()  # Sum of absolute values

tensor(24)