In [4]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)  # Enable gradient tracking
xx = torch.arange(4.0, requires_grad=True) # Alternative way to enable gradient tracking
x.grad  # Get the gradient

In [7]:
y = 2* torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward()  # Compute gradients
x.grad  # Print the gradient d y / d x

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad == 4 * x

tensor([True, True, True, True])

In [13]:
x.grad.zero_()  # Reset gradients
x.grad
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [14]:
x.grad.zero_()  # Reset gradients
x.grad
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [17]:
x.grad.zero_()  # Reset gradients
y = x*x
u = y.detach()  # Detach y from the computational graph
z = u * x
z.sum().backward()
x.grad  # Gradient only flows through x
# x.grad == u

tensor([0., 1., 4., 9.])

In [16]:
x.grad.zero_()  # Reset gradients
y.sum().backward()
x.grad  # No gradient flow through u

tensor([0., 2., 4., 6.])

In [18]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad == d/a

tensor(True)