In [3]:
import torch
from torch import nn
from d2l import torch as d2l

In [4]:
# 正向传播实现二维池化层
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = torch.max(X[i:i + p_h, j:j + p_w])
            elif mode == 'avg':
                Y[i, j] = torch.mean(X[i:i + p_h, j:j + p_w])
    return Y

In [7]:
X = torch.tensor([[0.0,1.0,2.0], [3.0,4.0,5.0], [6.0,7.0,8.0]])

print(pool2d(X, (2,2), mode='avg'))

tensor([[2., 3.],
        [5., 6.]])


In [8]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
print(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])


In [9]:
# 3x3最大池化层
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [10]:
pool2d = nn.MaxPool2d(3, stride=2, padding=1)
print(pool2d(X))

tensor([[[[ 5.,  7.],
          [13., 15.]]]])


In [11]:
pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
print(pool2d(X))

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])


In [12]:
X = torch.cat([X, X + 1], 1)  # 在通道维度上连结
print(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])


In [13]:
pool2d = nn.MaxPool2d(3, stride=2, padding=1)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])