In [1]:
import torch
from torch import nn

print(torch.device('cpu'))
print(torch.cuda.device('cuda'))
print(torch.cuda.device('cuda:0'))


cpu


In [2]:
# 查询可用的GPU数量
print(torch.cuda.device_count())

1


In [3]:
def try_gpu(i=0):
    """If GPU is available, return cuda:i; else return cpu."""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    """Return all available GPUs, or [cpu] if no GPU is available."""
    devices = [
        torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())
    ]
    return devices if devices else [torch.device('cpu')]

print(try_gpu())
print(try_gpu(10))
print(try_all_gpus())

cuda:0
cpu
[device(type='cuda', index=0)]


In [4]:
# 查询张量所在设备
x = torch.tensor([1, 2, 3])
print(x.device)

cpu


In [5]:
y = torch.tensor([3, 2, 1], device=try_gpu())
print(y.device)

cuda:0


In [6]:
Z = x.cuda(0)
print(Z)
print(Z.device)

tensor([1, 2, 3], device='cuda:0')
cuda:0


In [7]:
print(Z + y)

tensor([4, 4, 4], device='cuda:0')


In [12]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

print(net(Z.to(torch.float32).to(try_gpu())))

tensor([0.3819], device='cuda:0', grad_fn=<ViewBackward0>)
